# Generated by Django 2.0.1 on 2018-02-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('rg', models.BigIntegerField(unique=True, verbose_name='RG')),
                ('orgao', models.CharField(max_length=50, verbose_name='Órgão expedidor')),
                ('telefone', models.CharField(max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('observacao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
