# Generated by Django 2.0.2 on 2018-02-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_auto_20180205_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='cadastrador',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='rg',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='documento',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='telefone',
            field=models.CharField(max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
